remote_theme: jeffreytse/jekyll-theme-yat
favicon: 'data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>📜</text></svg>'
title: Too Long; Didn't Read
author: Casper da Costa-Luis
copyright: '(c) <a href="https://cdcl.ml">{author}</a> {currentYear}'
mailto_request: 'mailto:tldr@cdcl.ml?subject=request'
permalink: pretty
collections:
  posts:
    output: true
    permalink: /:title
defaults:
- scope:
    path: "_posts/*"
  values:
    layout: post
    author: Casper da Costa-Luis
    subtitle: TL;DR
    src_suffix: '/?utm_source=tldr.cdcl.ml'
baseurl: ""
url: https://tldr.cdcl.ml
google_analytics: G-MERR30FCLL
enableDNT: "false"
sitemap: true
lang: en-GB
yat:
  date_format: "%Y %b %d"
theme_color: coolblack
header_pages:
- archives.md
- categories.md
- tags.md
utterances:
  repo: casperdcl/tldr.cdcl.ml
  issue_term: title
  label: discussion
  theme: github-light
  follow_site_theme: true
plugins:
- jekyll-feed
- jekyll-glossary_tooltip
- jekyll-paginate
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
exclude:
- Gemfile
- Gemfile.lock
