# see https://github.com/actions/starter-workflows/blob/main/pages/jekyll.yml
name: Deploy Jekyll site to Pages
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  # allow GITHUB_TOKEN to deploy to GitHub Pages
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
        cache-version: 0
    - id: pages
      uses: actions/configure-pages@v1
    - run: bundle exec jekyll build --baseurl ${{ steps.pages.outputs.base_path }} # defaults output to '/_site'
      env:
        JEKYLL_ENV: production
    - uses: actions/upload-pages-artifact@v1 # This will automatically upload an artifact from the '/_site' directory
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - id: deployment
      uses: actions/deploy-pages@v1
