# see https://github.com/actions/starter-workflows/blob/main/pages/jekyll.yml
name: Deploy Jekyll site to Pages
on:
  push: {branches: [main]}
  workflow_dispatch:
# allow GITHUB_TOKEN to deploy to GitHub Pages
permissions: {contents: read, pages: write, id-token: write}
concurrency: {group: "pages", cancel-in-progress: true}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3'
        bundler-cache: true
        cache-version: 0
    - uses: actions/cache@v6
      with:
        path: .jekyll-cache/webmention_*.yml
        key: webmention
    - id: pages
      uses: actions/configure-pages@v6
    - name: jekyll build
      run: |
        bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}" # defaults output to '/_site'
        bundle exec jekyll webmention
      env:
        JEKYLL_ENV: production
    - uses: actions/upload-pages-artifact@v5 # automatically uploads an artifact from the '/_site' directory
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-slim
    needs: build
    steps:
    - id: deployment
      uses: actions/deploy-pages@v5
